export const FEATURED_PLAYLISTS_MERGE = 'FEATURED_PLAYLISTS_MERGE';
export const PLAYLIST_MERGE = 'PLAYLIST_MERGE';

export const TRACKS_SET = 'TRACKS_SET';
export const CURRENT_PLAYLIST_SET = 'CURRENT_PLAYLIST_SET';
